"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:yellow fg:surface0)\
$directory\
[](fg:yellow bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:blue)\
$docker_context\
[](fg:blue bg:purple)\
$time\
[ ](fg:purple)\
$line_break$character
"""

palette = "kanagawa_dragon"

[palettes.kanagawa_dragon]
base      = "#0d0c0c"   # sumi ink
surface0  = "#181616"   # dragon background
surface1  = "#282727"
text       = "#dcd7ba"  # parchment
subtext    = "#c5c9c5"  # fog

red        = "#c4746e"
green      = "#8a9a7b"
yellow     = "#c4b28a"
blue       = "#7fb4ca"
purple     = "#938aa9"
teal       = "#7aa89f"
orange     = "#e6c384"

bright_red    = "#e46876"
bright_green  = "#87a987"
bright_yellow = "#e6c384"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Macos = "󰀵"
Linux = "󰌽"
Arch = "󰣇"
Ubuntu = "󰕈"
Windows = "󰍲"

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:red"
format = '[ $user ]($style)'

[directory]
style = "fg:base bg:yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version ) ](fg:base bg:teal)]($style)'

[c]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version ) ](fg:base bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version ) ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version ) ](fg:base bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version ) ](fg:base bg:teal)]($style)'

[java]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version ) ](fg:base bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version ) ](fg:base bg:teal)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version ) ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version ) ](fg:base bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $context ) ](fg:base bg:blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:purple"
format = '[[  $time ](fg:base bg:purple)]($style)'

[line_break]
disabled = false

[character]
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
