-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
-- o
--
--
-- vim.api.nvim_create_autocmd("ColorScheme", {
--   callback = function()
--     vim.api.nvim_set_hl(0, "Comment", {
--       italic = true,
--     })
--
--     vim.api.nvim_set_hl(0, "Directory", {
--       fg = "#4FC1FF",
--     })
--
--     vim.api.nvim_set_hl(0, "LineNr", {
--       fg = "#5a5a5a",
--     })
--
--     vim.api.nvim_set_hl(0, "CursorLineNr", {
--       fg = "#cccccc",
--       bold = true,
--     })
--   end,
-- })
--
-- Apply highlights using the Neovim API
-- vim.api.nvim_set_hl(0, "SnacksPickerDirectory", { fg = "#89b4fa", bold = true })
-- vim.api.nvim_set_hl(0, "SnacksPickerPathHidden", { fg = "#585b70" })
-- vim.api.nvim_set_hl(0, "MiniIconsFolder", { fg = "#fab387" })

-- Better practice: Use an autocmd so colors stay if you swap themes
-- vim.api.nvim_create_autocmd("ColorScheme", {
--   pattern = "*",
--   callback = function()
--     vim.api.nvim_set_hl(0, "SnacksPickerDirectory", { fg = "#89b4fa", bold = true })
--     vim.api.nvim_set_hl(0, "SnacksPickerPathHidden", { fg = "#585b70" })
--   end,
-- })
